[package]
name = "double_ma_strategy"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = "1.0.204"
serde_json = "1.0.120"
chrono = "0.4"
vnrs = {path="../vnrs"}
